/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SW2.h"
#include "SW2_aliases.h"
#include "isr_GPIO_2.h"
#include "SW0.h"
#include "SW0_aliases.h"
#include "isr_GPIO_1.h"
#include "LED.h"
#include "LED_aliases.h"
#include "SW1.h"
#include "SW1_aliases.h"
#include "isr_GPIO_0.h"
#include "isr_GPIO_3.h"
#include "SW3.h"
#include "SW3_aliases.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "LED_GPIO0.h"
#include "LED_GPIO0_aliases.h"
#include "LED_GPIO1.h"
#include "LED_GPIO1_aliases.h"
#include "LED_GPIO2.h"
#include "LED_GPIO2_aliases.h"
#include "LED_GPIO3.h"
#include "LED_GPIO3_aliases.h"
#include "isr_GPIO_4.h"
#include "SW4.h"
#include "SW4_aliases.h"
#include "isr_GPIO_5.h"
#include "SW5.h"
#include "SW5_aliases.h"
#include "LED_GPIO4.h"
#include "LED_GPIO4_aliases.h"
#include "LED_GPIO5.h"
#include "LED_GPIO5_aliases.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

